In [1]:
import numpy as np
import pandas as pd

In [146]:
DataPrefix = "C:/Users/Public/Datasets/tez/"
prices_df = pd.read_csv(f"{DataPrefix}/twerche.csv", parse_dates=['date'])
#prices_df = prices_df.astype({'date': 'datetime64[ns, UTC]'}, copy=False)
#del proces_df

In [147]:
prices_df

           date    open     max     min   close      vol
0    1997-06-30  16.082  16.082  16.082  16.082  1735879
1    1997-07-01  16.339  16.339  16.339  16.339  3240026
2    1997-07-02  16.977  16.977  16.977  16.977  2972263
3    1997-07-03  17.184  17.184  17.184  17.184  1634564
4    1997-07-04  17.525  17.525  17.525  17.525   626717
...         ...     ...     ...     ...     ...      ...
5392 2019-01-17  70.200  70.200  69.700  69.900    28198
5393 2019-01-18  70.000  70.700  70.000  70.600    20213
5394 2019-01-21  70.700  70.700  69.700  70.500     9056
5395 2019-01-22  70.400  70.900  70.100  70.900    12747
5396 2019-01-23  70.800  70.900  70.500  70.800    12200

[5397 rows x 6 columns]

In [148]:
def get_df(file):
    prices_df = pd.read_csv(file,  parse_dates=['date'])
    #prices_df = prices_df.astype({'date': 'datetime64[ns, UTC]'}, copy=False)
    maxvol_df = prices_df[['date', 'vol']].groupby(prices_df['date'].map(lambda x: x.year)).agg('max')
    #maxvol_df['date'] = df_vol['date'].apply(lambda x: pd.Timestamp(x.year, x.month, x.day), axis=1)
    # I think index should be removed to pass auto tests...
    maxvol_df = maxvol_df.reset_index(drop=True)
    maxclose_df = prices_df[['date', 'close']].groupby(prices_df['date'].map(lambda x: x.year)).agg('max')
    maxclose_df = maxclose_df.reset_index(drop=True)
    return maxvol_df, maxclose_df

def solution(files):
    # files - any of available files, i.e:
    # files = ["./data/framp.csv", "./data/gnyned.csv", "./data/gwoomed.csv",
    #            "./data/hoilled.csv", "./data/plent.csv", "./data/throwsh.csv",
    #            "./data/twerche.csv", "./data/veeme.csv"]

    # write your solution here
    res = []
    for f in files:
        df_vol, df_close = get_df(f)
        res.append([df_vol, df_close])
    return res

In [149]:
df_vol, df_close = get_df(f"{DataPrefix}/framp.csv")

In [150]:
df_vol

         date        vol
0  2005-12-30  306208914
1  2006-12-29   28831088
2  2007-12-28   18388511
3  2008-12-31   24150048
4  2009-12-31   35246018
5  2010-12-31   54335576
6  2011-12-30   35866126
7  2012-12-28   59381774
8  2013-12-30   38320297
9  2014-12-30   21251451
10 2015-12-30   17545094
11 2016-12-30   17390752
12 2017-12-29   17621885
13 2018-12-28   28281682
14 2019-01-23    9451453

In [139]:
df_vol.dtypes

date    datetime64[ns]
vol              int64
dtype: object

In [151]:
df_close

         date   close
0  2005-12-30  2.8489
1  2006-12-29  2.8489
2  2007-12-28  4.5976
3  2008-12-31  4.1227
4  2009-12-31  3.6434
5  2010-12-31  3.2556
6  2011-12-30  3.8671
7  2012-12-28  4.4573
8  2013-12-30  5.7230
9  2014-12-30  4.7138
10 2015-12-30  6.4497
11 2016-12-30  5.4336
12 2017-12-29  6.8750
13 2018-12-28  7.0000
14 2019-01-23  7.5100