In [12]:
import pandas as pd
import numpy as np
import time
from io import StringIO

In [6]:
DataPrefix = "C:/Users/Public/Datasets/pandas/"
air_quality = pd.read_csv(f"{DataPrefix}/air_quality_no2_long.csv")
air_quality = air_quality.rename(columns={"date.utc": "datetime"})
#air_quality['datetime'] = pd.to_datetime(air_quality['datetime'])
air_quality = air_quality.astype({'datetime': 'datetime64[ns, UTC]'}, copy=False)
air_quality.dtypes

city                      object
country                   object
datetime     datetime64[ns, UTC]
location                  object
parameter                 object
value                    float64
unit                      object
dtype: object

In [7]:
data = np.zeros((2, ), dtype=[('A', 'i4'), ('B', 'f4'), ('C', 'a10')])
pd.DataFrame(data).dtypes

A      int32
B    float32
C     object
dtype: object

In [8]:
 df = pd.DataFrame({
        'one': pd.Series(np.random.randn(3), index=['a', 'b', 'c']),
        'two': pd.Series(np.random.randn(4), index=['a', 'b', 'c', 'd']),
        'three': pd.Series(np.random.randn(3), index=['b', 'c', 'd'])})
#df.dtypes
df

        one       two     three
a  0.010862 -1.363153       NaN
b  0.725767  1.750539 -0.117240
c  0.081802 -0.260869 -1.578420
d       NaN  0.276277 -0.236615

DataFrame has the methods add(), sub(), mul(), div() and related functions radd(), rsub(), … for carrying out binary operations. For broadcasting behavior, Series input is of primary interest. Using these functions, you can use to either match on the index or columns via the axis keyword:

In [42]:
row = df.iloc[1]
column = df['two']

df.sub(column, axis='index') # same as axis=0
df.sub(row, axis='columns') # same as axis=1, subtract row from df

        one       two     three
a -1.046597 -2.251666       NaN
b  0.000000  0.000000  0.000000
c -0.311062 -2.570640 -0.255129
d       NaN -0.687731 -0.550067

### Boolean reductions
You can apply the reductions: empty, any(), all(), and bool() to provide a way to summarize a boolean resul

In [46]:
df + df == df * 2
#(df + df == df * 2).all()

     one   two  three
a   True  True  False
b   True  True   True
c   True  True   True
d  False  True   True

### DateOffset objects

https://pandas.pydata.org/docs/user_guide/timeseries.html#timeseries-components

In the preceding examples, frequency strings (e.g. 'D') were used to specify a frequency that defined: how the date times in DatetimeIndex were spaced when using date_range() the frequency of a Period or PeriodIndex

Add 2 business days (Friday --> Tuesday)

```
In [147]: friday = pd.Timestamp('2018-01-05')

In [148]: friday.day_name()
Out[148]: 'Friday'

# Add 2 business days (Friday --> Tuesday)
In [149]: two_business_days = 2 * pd.offsets.BDay()

In [150]: two_business_days.apply(friday)
Out[150]: Timestamp('2018-01-09 00:00:00')

In [151]: friday + two_business_days
Out[151]: Timestamp('2018-01-09 00:00:00')

In [152]: (friday + two_business_days).day_name()
Out[152]: 'Tuesday'

```

In [19]:
t="""1449054136.83;15.31
1449054137.43;16.19
1449054138.04;19.22
1449054138.65;15.12
1449054139.25;13.12"""
df = pd.read_csv(StringIO(t), header=None, sep=';', index_col=[0])

dft = pd.to_datetime(df.index, unit='s')

df.index = pd.to_datetime(df.index, unit='s')

DatetimeIndex(['2015-12-02 11:02:16.829999924',
               '2015-12-02 11:02:17.430000067',
               '2015-12-02 11:02:18.039999962',
               '2015-12-02 11:02:18.650000095',
                  '2015-12-02 11:02:19.250000'],
              dtype='datetime64[ns]', name=0, freq=None)

In [25]:
%%timeit
df = pd.read_csv(StringIO(t), header=None, sep=';', index_col=[0])
#df.index = pd.to_datetime(df.index, unit='s')

2.16 ms ± 125 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [37]:
df.index = pd.DatetimeIndex(df.index, dtype='datetime64[ns]', freq=None)
df.dtypes

City     object
Event    object
Cost      int64
dtype: object

In [38]:
df.index

DatetimeIndex(['2018-01-06', '2018-04-06', '2018-07-06', '2018-10-06'], dtype='datetime64[ns]', freq=None)

In [21]:
def date_parser(string_list):
    return [time.ctime(float(x)) for x in string_list]

In [35]:
%%timeit
df = pd.read_csv(StringIO(t), parse_dates=[0],  sep=';', 
                 date_parser=date_parser, 
                 index_col='DateTime', 
                 names=['DateTime', 'X'], header=None)

4.3 ms ± 404 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [36]:
df.index

DatetimeIndex(['2018-01-06', '2018-04-06', '2018-07-06', '2018-10-06'], dtype='datetime64[ns]', freq=None)

In [33]:
# Let's create a dataframe 
df = pd.DataFrame({'City':['Lisbon', 'Parague', 'Macao', 'Venice'], 
                    'Event':['Music', 'Poetry', 'Theatre', 'Comedy'], 
                    'Cost':[10000, 5000, 15000, 2000]}) 
  
  
# Let's create an index using Timestamps 
index_ = [pd.Timestamp('01-06-2018'), pd.Timestamp('04-06-2018'), 
          pd.Timestamp('07-06-2018'), pd.Timestamp('10-06-2018')] 
  
# Let's set the index of the dataframe 
df.index = index_ 
  
# Let's visualize the dataframe 
df.dtypes

City     object
Event    object
Cost      int64
dtype: object

In [41]:
type(df.index)

pandas.core.indexes.datetimes.DatetimeIndex

In [42]:
sorted([9, 11, 7])

[7, 9, 11]